server:
  port: 80


spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hmit?ServerTiomZone=UTC
        username: root
        password: 666666

#下面只有在前缀读取不出来的情况下才开始使用
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix:       #这里是字节的前缀,  带_的
